# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import loftr_pb2 as loftr__pb2


class LoftrStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getEssentialMatrix = channel.unary_unary(
                '/LOFRT.Loftr/getEssentialMatrix',
                request_serializer=loftr__pb2.ImagePair.SerializeToString,
                response_deserializer=loftr__pb2.GetEssentialMatrixReply.FromString,
                )


class LoftrServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getEssentialMatrix(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoftrServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getEssentialMatrix': grpc.unary_unary_rpc_method_handler(
                    servicer.getEssentialMatrix,
                    request_deserializer=loftr__pb2.ImagePair.FromString,
                    response_serializer=loftr__pb2.GetEssentialMatrixReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LOFRT.Loftr', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Loftr(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getEssentialMatrix(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LOFRT.Loftr/getEssentialMatrix',
            loftr__pb2.ImagePair.SerializeToString,
            loftr__pb2.GetEssentialMatrixReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
