# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: loftr.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='loftr.proto',
  package='LOFRT',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bloftr.proto\x12\x05LOFRT\"A\n\x05Image\x12\x12\n\x05image\x18\x01 \x01(\x0cH\x00\x88\x01\x01\x12\x11\n\x04path\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x08\n\x06_imageB\x07\n\x05_path\"G\n\tImagePair\x12\x1c\n\x06imageA\x18\x01 \x01(\x0b\x32\x0c.LOFRT.Image\x12\x1c\n\x06imageB\x18\x02 \x01(\x0b\x32\x0c.LOFRT.Image\"%\n\x06Tensor\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\x12\r\n\x05shape\x18\x02 \x03(\x05\"H\n\x17GetEssentialMatrixReply\x12\x1d\n\x06matrix\x18\x01 \x01(\x0b\x32\r.LOFRT.Tensor\x12\x0e\n\x06status\x18\x02 \x01(\x05\x32Q\n\x05Loftr\x12H\n\x12getEssentialMatrix\x12\x10.LOFRT.ImagePair\x1a\x1e.LOFRT.GetEssentialMatrixReply\"\x00\x62\x06proto3'
)




_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='LOFRT.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='LOFRT.Image.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='path', full_name='LOFRT.Image.path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_image', full_name='LOFRT.Image._image',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_path', full_name='LOFRT.Image._path',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=22,
  serialized_end=87,
)


_IMAGEPAIR = _descriptor.Descriptor(
  name='ImagePair',
  full_name='LOFRT.ImagePair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='imageA', full_name='LOFRT.ImagePair.imageA', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imageB', full_name='LOFRT.ImagePair.imageB', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=160,
)


_TENSOR = _descriptor.Descriptor(
  name='Tensor',
  full_name='LOFRT.Tensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='LOFRT.Tensor.data', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shape', full_name='LOFRT.Tensor.shape', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=199,
)


_GETESSENTIALMATRIXREPLY = _descriptor.Descriptor(
  name='GetEssentialMatrixReply',
  full_name='LOFRT.GetEssentialMatrixReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='matrix', full_name='LOFRT.GetEssentialMatrixReply.matrix', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='LOFRT.GetEssentialMatrixReply.status', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=273,
)

_IMAGE.oneofs_by_name['_image'].fields.append(
  _IMAGE.fields_by_name['image'])
_IMAGE.fields_by_name['image'].containing_oneof = _IMAGE.oneofs_by_name['_image']
_IMAGE.oneofs_by_name['_path'].fields.append(
  _IMAGE.fields_by_name['path'])
_IMAGE.fields_by_name['path'].containing_oneof = _IMAGE.oneofs_by_name['_path']
_IMAGEPAIR.fields_by_name['imageA'].message_type = _IMAGE
_IMAGEPAIR.fields_by_name['imageB'].message_type = _IMAGE
_GETESSENTIALMATRIXREPLY.fields_by_name['matrix'].message_type = _TENSOR
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['ImagePair'] = _IMAGEPAIR
DESCRIPTOR.message_types_by_name['Tensor'] = _TENSOR
DESCRIPTOR.message_types_by_name['GetEssentialMatrixReply'] = _GETESSENTIALMATRIXREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'loftr_pb2'
  # @@protoc_insertion_point(class_scope:LOFRT.Image)
  })
_sym_db.RegisterMessage(Image)

ImagePair = _reflection.GeneratedProtocolMessageType('ImagePair', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEPAIR,
  '__module__' : 'loftr_pb2'
  # @@protoc_insertion_point(class_scope:LOFRT.ImagePair)
  })
_sym_db.RegisterMessage(ImagePair)

Tensor = _reflection.GeneratedProtocolMessageType('Tensor', (_message.Message,), {
  'DESCRIPTOR' : _TENSOR,
  '__module__' : 'loftr_pb2'
  # @@protoc_insertion_point(class_scope:LOFRT.Tensor)
  })
_sym_db.RegisterMessage(Tensor)

GetEssentialMatrixReply = _reflection.GeneratedProtocolMessageType('GetEssentialMatrixReply', (_message.Message,), {
  'DESCRIPTOR' : _GETESSENTIALMATRIXREPLY,
  '__module__' : 'loftr_pb2'
  # @@protoc_insertion_point(class_scope:LOFRT.GetEssentialMatrixReply)
  })
_sym_db.RegisterMessage(GetEssentialMatrixReply)



_LOFTR = _descriptor.ServiceDescriptor(
  name='Loftr',
  full_name='LOFRT.Loftr',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=275,
  serialized_end=356,
  methods=[
  _descriptor.MethodDescriptor(
    name='getEssentialMatrix',
    full_name='LOFRT.Loftr.getEssentialMatrix',
    index=0,
    containing_service=None,
    input_type=_IMAGEPAIR,
    output_type=_GETESSENTIALMATRIXREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOFTR)

DESCRIPTOR.services_by_name['Loftr'] = _LOFTR

# @@protoc_insertion_point(module_scope)
